### ISSUE TITLE
To increase the request length limit

### ISSUE THREAD

**Issue by yukozh** [PipeCI/BlobStorage#1]
Functional tests failed on linux and osx.

https://travis-ci.org/PipeCI/BlobStorage

The request length limits exceeded. We should increase the request length limit.

**Comment by JaymzZh** [comment]
This is due to corefx issue [#1936](https://github.com/CodeComb/Extensions/blob/322b1a83f0e24cf4bf658679102c61fb64fe0487/src/CodeComb.AspNet.Extensions/Others/ImageExtensions.cs)
